### PR TITLE
Delete old intro files and update README

### PR DESCRIPTION
**Pull request by ShaanGondalia**
Documentation updates for virtual intro project.

### CODE REVIEW

**Comment by rabinowitz** [comment]
Can we keep around last year's intro project rather than deleting it, maybe by having `intro-project/2019` and `intro-project/2020` folders, or by making an `intro-project/archive/2019` folder? We may want to use it or adapt it in the future when we're back in person.

**Comment by ShaanGondalia** [comment]
Fixed some typos and added the old files back into an archive folder, should be good to merge.

**Comment by rabinowitz** [comment]
LGTM. Make sure to squash and merge.

**Review by muthuArivoli — APPROVED** [review]
LGTM

**Pull request merged**
